import type { Metadata } from "next";
import "./globals.css";
import GradientBg from "./_components/gradient";
import Header from "./_components/header";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative h-screen flex flex-col">
             <Header className="content" />
          <div className="absolute inset-0 -z-10">
            <GradientBg />
          </div>
            {children}
      </body>
    </html>
  );
}
